---
version: '2'
services:
  db:
    image: influxdb 
    container_name: influxdb
    networks:
      - default
    volumes:
       - /srv/dev-disk-by-label-HddStorage/Containers/speedtest:/var/lib/influxdb
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_DB=speedtest
    restart: unless-stopped
  web:
    image: leeviewp/internet-speedtest-docker-raspbian:speedweb
    container_name: speedweb
    ports:
      - "3000:3000"
    networks:
      - default
    environment:
      - GF_SERVER_ROOT_URL=http://localhost
      - GF_SECURITY_ADMIN_PASSWORD=teste
    restart: unless-stopped
  testing:
    image: leeviewp/internet-speedtest-docker-raspbian:speedtest
    container_name: speedtest
    networks:
      - default
    environment:
      - TEST_INTERVAL=300
    restart: unless-stopped
networks:
  default:
    driver: bridge